modLoader = "javafml"
loaderVersion = "*"
license = "MIT"
issueTrackerURL = "https://github.com/123FLO321/vineclipper/issues"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "Flo0815"
description = '''
${description}
'''

[[mixins]]
config = "vineclipper.mixins.json"

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "BOTH"
